#!/usr/bin/env python3
"""Build the dependency-free single-file runner from maintained package sources.

Only regular Python source files below src/am_i_nerfed are included. ZIP_STORED,
fixed metadata, and sorted paths make the generated bytes reproducible across
Python/zlib versions. No build backend, installation, or network is required.
"""

import argparse
import ast
import base64
import hashlib
import io
import os
from pathlib import Path
import re
import sys
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "am_i_nerfed"
OUTPUT = ROOT / "am-i-nerfed.py"
_MODULE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def package_sources(package=PACKAGE):
    """Allowlist Python modules; never copy caches, logs, credentials, or links."""
    package = Path(package)
    if package.is_symlink() or not package.is_dir():
        raise ValueError("Expected a regular src/am_i_nerfed package directory")
    files = []
    for path in package.rglob("*"):
        relative = path.relative_to(package)
        if "__pycache__" in relative.parts or any(part.startswith(".") for part in relative.parts):
            continue
        if path.is_symlink():
            raise ValueError("Source symlinks are not allowed in the standalone bundle")
        if not path.is_file() or path.suffix != ".py":
            continue
        if any(not _MODULE.fullmatch(part) for part in relative.parts[:-1]) or not _MODULE.fullmatch(path.stem):
            raise ValueError("Invalid Python module path in standalone source tree")
        files.append(("am_i_nerfed/" + relative.as_posix(), path.read_bytes()))
    required = {"am_i_nerfed/__init__.py", "am_i_nerfed/__main__.py", "am_i_nerfed/cli.py"}
    if not required.issubset(name for name, _ in files):
        raise ValueError("Standalone source tree is missing package entry points")
    return sorted(files)


def package_version(files):
    source = dict(files)["am_i_nerfed/__init__.py"]
    tree = ast.parse(source, filename="am_i_nerfed/__init__.py")
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "__version__"
                                                for target in node.targets):
            value = ast.literal_eval(node.value)
            if isinstance(value, str) and re.fullmatch(r"[0-9][A-Za-z0-9.+-]*", value):
                return value
    raise ValueError("Package must declare a literal __version__ string")


def archive_bytes(files):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED, allowZip64=False) as archive:
        for name, data in sorted(files):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.create_version = 20
            info.extract_version = 20
            info.external_attr = 0o100644 << 16
            info.internal_attr = 0
            info.extra = b""
            info.comment = b""
            archive.writestr(info, data)
    return output.getvalue()


_PREFIX = '''#!/usr/bin/env python3
# Generated by scripts/build_standalone.py. Do not edit this file by hand.
# Contains only the maintained am_i_nerfed Python sources; no runtime downloads.
"""Am I Nerfed? — standalone runner (Python 3.9+, standard library only).

Run: python3 am-i-nerfed.py [args]
Pipe: cat am-i-nerfed.py | python3 - [args]
With no arguments, scan every discovered model on every installed supported tool.
The embedded hash checks payload integrity; it is not a publisher signature.
"""

import base64
import hashlib
import os
from pathlib import Path
import sys
import tempfile

'''

_SUFFIX = '''


def _clear_package_modules():
    # Prefer the embedded sources even if a startup customization imported an
    # installed version before this script ran. Changes affect this process only.
    for name in tuple(sys.modules):
        if name == "am_i_nerfed" or name.startswith("am_i_nerfed."):
            del sys.modules[name]


def main(argv=None):
    if sys.version_info < (3, 9):
        print("Am I Nerfed? requires Python 3.9 or newer.", file=sys.stderr)
        return 1
    try:
        payload = base64.b85decode(_PAYLOAD_B85)
    except (ValueError, TypeError):
        print("Standalone payload is invalid; obtain a fresh copy.", file=sys.stderr)
        return 1
    if hashlib.sha256(payload).hexdigest() != _PAYLOAD_SHA256:
        print("Standalone payload integrity check failed; obtain a fresh copy.", file=sys.stderr)
        return 1
    # TemporaryDirectory creates a private directory; the embedded ZIP is 0600.
    # Import straight from the ZIP without extracting files or installing code.
    with tempfile.TemporaryDirectory(prefix="am-i-nerfed-standalone-") as directory:
        archive = str(Path(directory) / "package.zip")
        fd = os.open(archive, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "wb") as stream:
            stream.write(payload)
        _clear_package_modules()
        sys.path.insert(0, archive)
        try:
            from am_i_nerfed.cli import main as cli_main
            return cli_main(argv)
        finally:
            _clear_package_modules()
            try:
                sys.path.remove(archive)
            except ValueError:
                pass


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("Interrupted; completed local evidence is retained.", file=sys.stderr)
        sys.exit(130)
'''


def build(package=PACKAGE):
    files = package_sources(package)
    payload = archive_bytes(files)
    encoded = base64.b85encode(payload).decode("ascii")
    lines = "\n".join("    b\"" + encoded[start:start + 100] + "\"" for start in range(0, len(encoded), 100))
    metadata = ("_VERSION = " + repr(package_version(files)) + "\n"
                "_PAYLOAD_SHA256 = " + repr(hashlib.sha256(payload).hexdigest()) + "\n"
                "_PAYLOAD_B85 = (\n" + lines + "\n)\n")
    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8").strip()
    license_comments = "\n".join("# " + line if line else "#" for line in license_text.splitlines())
    prefix = _PREFIX.replace('"""Am I Nerfed?', license_comments + '\n\n"""Am I Nerfed?', 1)
    return (prefix + metadata + _SUFFIX).encode("utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit nonzero if am-i-nerfed.py is missing or stale")
    args = parser.parse_args(argv)
    try:
        generated = build()
        if args.check:
            if not OUTPUT.is_file() or OUTPUT.read_bytes() != generated:
                print("am-i-nerfed.py is missing or stale; run python3 scripts/build_standalone.py", file=sys.stderr)
                return 1
            print("am-i-nerfed.py is current.")
            return 0
        fd, temporary = tempfile.mkstemp(prefix=".am-i-nerfed-build-", dir=str(OUTPUT.parent))
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(generated)
            os.chmod(temporary, 0o644)
            os.replace(temporary, OUTPUT)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
        print("Built am-i-nerfed.py (%d bytes)." % len(generated))
        return 0
    except (OSError, ValueError, SyntaxError) as exc:
        print("Cannot build standalone runner: " + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
